[package]
name = "consolidated_execution"
version = "0.1.0"
authors = ["happysalada <raphael.megzari@gmail.com>"]

[dependencies]
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"
rust_decimal = "0.9.1"
chrono = {version = "0.4.4",features = ["serde"]}
